pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git url: 'https://https://github.com/arunsankarcm/Training-Calendar', branch: 'main'
            }
        }
        stage('Build') {
            steps {
                echo 'Building...'
                // Add your build commands
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                // Add your test commands
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                // Add your deployment commands
            }
        }
    }
}
